.. links, substitutions to include across pages.
.. vim: ft=rst

.. This project
.. _nb2plots code:
.. _nb2plots github: http://github.com/matthew-brett/nb2plots
.. _nb2plots pypi: http://pypi.python.org/pypi/nb2plots
.. _nb2plots issue tracker:
.. _nb2plots issues: http://github.com/matthew-brett/nb2plots/issues
.. _nb2plots travis-ci: https://travis-ci.org/matthew-brett/nb2plots
.. _documentation: https://matthew-brett.github.com/nb2plots

.. Code support
.. _versioneer: https://github.com/warner/python-versioneer
.. _setuptools intro:
   http://packages.python.org/an_example_pypi_project/setuptools.html

.. Relevant projects
.. _pandoc: http://pandoc.org
.. _jupyter: jupyter.org
.. _homebrew: brew.sh
.. _sphinx: http://sphinx-doc.org
.. _rest: http://docutils.sourceforge.net/rst.html
.. _`Sphinx reST`: http://sphinx.pocoo.org/rest.html
.. _reST: http://docutils.sourceforge.net/rst.html
.. _matplotlib plot directive: http://matplotlib.org/sampledoc/extensions.html
.. _nbconvert: http://nbconvert.readthedocs.org/en/latest/
.. _ipython: http://ipython.org/
.. _docutils: http://docutils.sourceforge.net
.. _rst2md project: https://github.com/cgwrench/rst2md

.. Python and common libraries
.. _python: https://www.python.org
.. _python standard library: http://docs.python.org/3/library
.. _python.org releases: http://www.python.org/download/releases
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _matplotlib: http://matplotlib.org/
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _mock: https://github.com/testing-cabal/mock
.. _pip: http://pypi.python.org/pypi/pip
.. _PEP8:
   https://www.python.org/dev/peps/pep-0008/
.. _Python glossary:
    https://docs.python.org/3/glossary.html
.. _pypi: http://pypi.python.org/pypi

.. Licenses
.. _GPL: http://www.gnu.org/licenses/gpl.html
.. _BSD: http://www.opensource.org/licenses/bsd-license.php

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:
.. |nbplot-documentation| replace:: :ref:`nbplots-documentation`
.. |code-links-documentation| replace:: :ref:`code-links-documentation`
