#!python
""" Convert notebook to ReST format with plot directives

Example:

    nb2plots example.ipynb

Prints to stdout
"""
# vim: ft=python
from __future__ import division, print_function, absolute_import

import sys
from optparse import OptionParser

from nb2plots import __version__
from nb2plots.from_notebook import convert_nb_fname

# Bytes stream for writing to stdout
bin_stdout = sys.stdout.buffer if sys.version_info[0] > 2 else sys.stdout


def main():
    parser = OptionParser(
        usage="%s NOTEBOOK_FNAME\n\n" % sys.argv[0] + __doc__,
        version="%prog " + __version__)
    (opts, notebooks) = parser.parse_args()
    if len(notebooks) != 1:
        parser.print_help()
        sys.exit(1)
    rst_text = convert_nb_fname(notebooks[0]) + '\n'
    bin_stdout.write(rst_text.encode('utf8'))


if __name__ == '__main__':
    main()
