#!python
""" Convert notebook to ReST format with plot directives

Example:

    nb2plots example.ipynb

Prints to stdout
"""
# vim: ft=python
from __future__ import division, print_function, absolute_import

import sys
from argparse import ArgumentParser

from nb2plots.from_notebook import convert_nb_fname

# Bytes stream for writing to stdout
bin_stdout = sys.stdout.buffer if sys.version_info[0] > 2 else sys.stdout


def main():
    parser = ArgumentParser(
        description="Convert notebook to ReST format with plot directives")
    parser.add_argument('notebook', help = 'notebook file to convert')
    args = parser.parse_args()
    rst_text = convert_nb_fname(args.notebook) + '\n'
    bin_stdout.write(rst_text.encode('utf8'))


if __name__ == '__main__':
    main()
