#!python
""" Convert single ReST document to notebook JSON

Example:

    plots2nb example.rst

Write to <fname>.ipynb by default.
"""
# vim: ft=python
from __future__ import division, print_function, absolute_import

import sys
from argparse import ArgumentParser

from nb2plots.to_notebook import rst2ipynb

# Bytes stream for writing to stdout
bin_stdout = sys.stdout.buffer if sys.version_info[0] > 2 else sys.stdout


def main():
    parser = ArgumentParser(
        description="Convert ReST file to notebook JSON")
    parser.add_argument('rst_file', help = 'ReST file to convert')
    parser.add_argument('-W', '--warn-is-error', action='store_true',
                        help = 'turn warnings into errors')
    args = parser.parse_args()
    with open(args.rst_file, 'rt') as fobj:
        contents = fobj.read()
    ipynb_json = rst2ipynb(contents,
                           status=sys.stderr,
                           warningiserror=args.warn_is_error)
    bin_stdout.write(ipynb_json)


if __name__ == '__main__':
    main()
