#!python
""" Convert single ReST document to Python .py file text

Example:

    sphinx2py example.rst

Write .py file text to stdout as UTF-8.
"""
# vim: ft=python

from nb2plots.converters import to_py
from nb2plots.commands import do_main


if __name__ == '__main__':
    do_main("Convert Sphinx ReST file to Python code", to_py)
